'\" t
.\"     Title: blkmenu
.\"    Author: Giacomo Comitti
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07.09.2019
.\"    Manual: BLKMENU
.\"    Source: BLKMENU 0.3
.\"  Language: English
.\"
.TH "BLKMENU" "1" "07\&.09\&.2019" "BLKMENU 0\&.3" "BLKMENU"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
blkmenu \- tiny curses wrapper around lsblk and udisksctl\&.
.SH "SYNOPSIS"
.sp
\fBblkmenu\fR [OPTIONS]
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Print help information\&.
.RE
.PP
\fB\-V, \-\-version\fR
.RS 4
Print version information\&.
.RE
.PP
\fB\-\-border\fR
.RS 4
Show menu border\&.
.RE
.PP
\fB\-\-no\-border\fR
.RS 4
Don\(cqt show menu border\&. This is the default behavior\&.
.RE
.PP
\fB\-\-title\fR \fITITLE\fR
.RS 4
Set menu title\&. Shown only when the border is enabled\&. Default value: " blkmenu "
.RE
.PP
\fB\-\-no\-title\fR
.RS 4
Don\(cqt show menu title\&. Same as
\fB\-\-title\fR
""\&.
.RE
.PP
\fB\-\-columns\fR \fICOLUMNS\fR
.RS 4
Show only the given device properties\&. See
lsblk \-\-help
for a list of all available properties\&.

Default value: "name,>size,type,fstype,partlabel,label,rm,ro,mountpoint"
.RE
.PP
\fB\-\-header\fR
.RS 4
Show column headers\&. Enabled by default\&.
.RE
.PP
\fB\-\-no\-header\fR
.RS 4
Hide column headers\&.
.RE
.PP
\fB\-\-flat\fR
.RS 4
Don\(cqt show hierarchy relationships between devices\&.
.RE
.PP
\fB\-\-tree\fR [\fICOLUMN_NAME\fR]
.RS 4
The column displayed as hierarchy tree\&. Defaults to the first column\&.
.RE
.PP
\fB\-\-stretch\fR
.RS 4
Stretch columns to fill the whole window\&. This is the default behavior\&.
.RE
.PP
\fB\-\-no\-stretch\fR
.RS 4
Don\(cqt stretch columns to fill the whole window\&. Columns will be separated by the separator set with the
\fB\-\-sep\fR
option\&.
.RE
.PP
\fB\-\-sep\fR \fISEPARATOR\fR
.RS 4
String used to separate columns when
\fB\-\-no\-stretch\fR
is given\&.

Default value: " "
.RE
.PP
\fB\-\-open\fR \fICMD\fR
.RS 4
Command used to open a device mountpoint\&.

Default value: the value of
$SHELL
or "/bin/sh", in this order
.RE
.PP
\fB\-\-mount\-opts\fR \fIOPTS\fR
.RS 4
Default mount options\&.

Default value: "nosuid,noexec,noatime"
.RE
.PP
\fB\-\-vifm\fR [\fISERVER_NAME\fR]
.RS 4
Vifm server name\&. Bypass the
\fB\-\-open\fR
option and open the device mountpoint directly in the vifm instance named
\fISERVER_NAME\fR\&.

Default value: "vifm"
.RE
.PP
\fB\-f\fR \fIEXPR\fR [\fIEXPR\fR \&...]
.RS 4
Exclude devices that match any of the given expression rules\&.

See the
FILTER EXPRESSIONS
section\&.
.RE
.PP
\fB\-p\fR \fIEXPR\fR [\fIEXPR\fR \&...]
.RS 4
Exclude devices and all their descendants that match any of the given expression rules\&.

See the
FILTER EXPRESSIONS
section\&.
.RE
.PP
\fB\-a\fR \fIKEY:ACTION\fR [\fIKEY:ACTION\fR \&...]
.RS 4
Bindings as
\fIkey:action\fR
pairs\&. Arrow keys can be mapped by using the special strings "KEY_UP", "KEY_DOWN", "KEY_LEFT" and "KEY_RIGHT"\&.

See the
AVAILABLE ACTIONS
section\&.
.RE
.PP
\fB\-A\fR \fIKEY:ACTION\fR [\fIKEY:ACTION\fR \&...]
.RS 4
Bindings as
\fIkey:action\fR
pairs\&. Same as
\fB\-a\fR
but clears other bindings that map to the same action\&. Arrow keys can be mapped by using the special strings "KEY_UP", "KEY_DOWN", "KEY_LEFT" and "KEY_RIGHT"\&.

See the
AVAILABLE ACTIONS
section\&.
.RE
.SH "AVAILABLE ACTIONS"
.sp
\fBquit\fR Exit the program\&.
.sp
\fBmovedown\fR Move down a line\&.
.sp
\fBmoveup\fR Move up a line\&.
.sp
\fBmount\fR Mount the selected device\&.
.sp
\fBunmount\fR Unmount the selected device\&.
.sp
\fBlock\fR Lock selected device\&.
.sp
\fBunlock\fR Unlock selected device\&.
.sp
\fBeject\fR Eject selected device\&.
.sp
\fBopen\fR Open the selected device mountpoint with the given \fB\-\-open\fR command\&.
.sp
\fBinfo\fR Display all device properties\&.
.sp
\fBrefresh\fR Refresh the device tree\&.
.sp
\fBtoggle_filter\fR Toggle active filters (set with \fB\-f\fR or \fB\-p\fR)\&.
.sp
\fBhelp\fR Display help screen\&.
.SH "DEFAULT BINDINGS"
.sp
\fBq\fR quit
.sp
\fBj or KEY_DOWN\fR movedown
.sp
\fBk or KEY_UP\fR moveup
.sp
\fBm\fR mount
.sp
\fBu\fR unmount
.sp
\fBl\fR lock
.sp
\fBL\fR unlock
.sp
\fBe\fR eject
.sp
\fBo\fR open
.sp
\fBi\fR info
.sp
\fBr\fR refresh
.sp
\fBa\fR toggle_filter
.sp
\fB?\fR help
.SH "FILTER EXPRESSIONS"
.sp
Filters are expected to be python conditional expressions\&. To refer to device properties you can use the same identifiers you would use for the \fB\-\-columns\fR option\&. For a list of all available identifiers see \fIlsblk \-\-help\fR\&. The \fImatch\fR and \fIsearch\fR functions of the \fIre\fR python module are also available\&.
.SS "Example expressions:"
.sp
\fB"not mountpoint"\fR Display only mounted devices\&.
.sp
\fB"\fR\fB\fIsda\fR\fR\fB in path"\fR Display only devices whose path doesn\(cqt contain the string \fIsda\fR\&.
.sp
\fB"name == \fR\fB\fIsda\fR\fR\fB"\fR Hide devices whose name is \(cqsda\(cq\&.
.sp
\fB"name\&.startswith(\fR\fB\fIsda\fR\fR\fB)"\fR Hide devices whose name starts with \fIsda\fR\&.
.SH "RESOURCES"
.sp
\fBProject site:\fR https://github\&.com/gcmt/blkmenu
.SH "LICENSE"
.sp
Copyright \(co 2019 Giacomo Comitti\&.
.sp
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.sp
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.sp
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.SH "AUTHOR"
.PP
\fBGiacomo Comitti\fR
.RS 4
Author.
.RE
